config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:create]
    resources :reviews, only: [:create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :cocktail, presence: true, uniqueness: { scope: :ingredient }
  # validates :ingredient, presence: true, uniqueness: true
  validates :description, presence: true
  # validates  uniqueness: { scope: :description }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  # validates :name, uniqueness: true, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cocktails
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
    @review = Review.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
   def new
     @cocktail = Cocktail.find(params[:cocktail_id])
     @dose = Dose.new
   end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      @review = Review.new
      render "cocktails/show"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      @dose = Dose.new
      render "cocktails/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_drink.html.erb
<tr>
  <div class="mt-3 mb-3">
    <td><%= @cocktails.name %></td>
  </div>

</tr>

app/views/cocktails/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 mt-5">
      <%= simple_form_for(@cocktail) do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file, label: ('Upload cocktail photo').html_safe %>
      <div class="button-submit">
        <%= f.button :submit %>
      </div>

      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="container col-12 col-md-8 col-sm-4">
  <div class="text-center mt-3 mb-3">
      <h1>Cocktail list</h1>
  </div>
    <div class="row justify-content-around mt-3 mb-3 ml-3 mr-3">
      <% @cocktails.each do |cocktail| %>
        <div class="card col-12 col-md-8 col-sm-4 mb-3 mt-3">
          <%= cocktail.name %>
          <%= render 'drink', cocktail: cocktail %>
                <% if cocktail.photo.attached? %>
                  <a href=" <%= cocktail_url(cocktail) %> "><%= cl_image_tag cocktail.photo.key, height: 300, width: 300, crop: :fill %>
                     <div class="drink-card-img mt-3 mb-3">
                      <div class="overlay">
                        <div class="text-hover">Click to read more!</div>
                        </div>
                      </div>
                  </a>
                <% end %>
        </div>
      <% end %>
    </div>
</div>

app/views/cocktails/new.html.erb
<div class="text-center mt-3">
  <h1>Create cocktail</h1>
</div>
  <%= render 'form', Cocktail: @cocktail %>
    <div class="button-back ml-3">
      <%= link_to 'Back', cocktails_path %>
    </div>

app/views/cocktails/show.html.erb
<div class="container col-12 col-md-6 col-sm-4">
  <div class="mt-3 mb-3">
    <h1><%= @cocktail.name %></h1>
  </div>
  <div class="image">
    <% if @cocktail.photo.attached? %>
      <%= cl_image_tag @cocktail.photo.key, height: 300, width: 400, crop: :fill %>
    <% end %>
  </div>
    <div class="col-sm-12 col-md-6">
      <%= render "doses/new", cocktail: @cocktail, dose: @dose %>
    </div>
<div class="mt-3 bm-3">
  <h4>Reviews</h4>
</div>

        <% if @cocktail.reviews.empty? %>
      <p>Be the first to let a review</p>
    <% else %>
      <ul class="list-group">
        <% @cocktail.reviews.each do |review| %>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <span class="badge badge-primary badge-pill">
              <% counter = 0 %>
              <% 5.times do %>
                <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
                <% counter += 1 %>
              <% end %>
            </span>
            <%= review.content %>
          </li>
        <% end %>
      </ul>
    <% end %>
    <%= render "reviews/new", cocktail: @cocktail, review: @review %>


    <div class="col-sm-12 col-md-6 mt-3 mb-3">
      <h3>Recipe</h3>

      <table class="table table-bordered mt-3 mb-3">
        <tbody>
          <thead>
            <th>Ingredient</th>
            <th>Description</th>
            <th>Action</th>
          </thead>
            <% @cocktail.doses.each do |dose| %>
            <tr>
              <td><%= dose.ingredient.name %></td>
              <td><%= dose.description %></td>
              <td>
                <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <i class="fa fa-trash destroy_dose"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>

     <div class="button">
    <%= link_to "Back to all cocktails", root_path %>
  </div>
      </div>
    </div>

app/views/doses/_new.html.erb
<div class="mb-3 mt-3">
  <h3>Add a new dose</h3>
</div>

<%= simple_form_for [cocktail, dose] do |f| %>
  <%= f.association :ingredient, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/doses/new.html.erb
<h1> New:<%= @cocktail.name %></h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <link rel="icon" type="image/png" href="https://media.istockphoto.com/vectors/brown-and-white-tablecloth-argyle-pattern-vector-id936155374?k=6&m=936155374&s=170667a&w=0&h=r5btubMlhOF9PlujIRLz5-6vizSsLQ4nIjGSYkEju_8=">

   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta property="og:image" content="https://www.discoverlosangeles.com/sites/default/files/styles/hero/public/images/2019-12/Death%20%26%20Co%20DTLA%20Main%20Bar.jpg?itok=kk9P363v">
    <meta property="og:image:type" content="image/jpeg">
    <meta property="og:image:width" content="200">
    <meta property="og:image:height" content="200">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.discoverlosangeles.com/sites/default/files/styles/hero/public/images/2019-12/Death%20%26%20Co%20DTLA%20Main%20Bar.jpg?itok=kk9P363v);">
  <div class="container">
    <h1>Welocme at the bar!</h1>
    <p>Serve your selfe and add the drink!</p>
    <div class="banner-button">
      <a> <%= link_to 'Add cocktail/drink', new_cocktail_path %></%></a>
    </div>

  </div>
</div>
    <%= yield %>


  </body>
  <div class="justify-content-center text-center mt-3 mb-3">
      <footer>
      <p>Copyright by Lukasz Koziel 2020</p>
    </footer>
    </div>
</html>

app/views/reviews/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 mt-5">
      <%= simple_form_for[@cocktail, @review] do |f| %>
      <%= f.input :content %>
      <%= f.input :rating %>
      <%= f.button :submit  class: 'btn btn-primary'%>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/_new.html.erb
<div class="mt-3 mb-3">
<h2>Give review for <%= @cocktail.name %> </h2>
</div>
<%= simple_form_for [cocktail, review] do |f| %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.input :content %>
  <%= f.submit class: "btn btn-primary mb-3"%>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to cocktails_path, class: "navbar-brand" do %>
  <div class="text-light">
    <i class="fas fa-cocktail"></i>
  </div>

    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", cocktails_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown bg-light">
          <%= image_tag "550751-200.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="login">
               <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>

          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>